---
- name: Install LAMP stack
  hosts: appdb
  become: yes

  tasks:
    - name: Install Apache
      package:
        name: httpd
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install MariaDB (MySQL)
      package:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install PHP and extensions
      package:
        name:
          - php
          - php-mysqlnd
          - php-cli
          - php-gd
          - php-xml
          - php-mbstring
        state: present

    - name: Restart Apache after PHP install
      service:
        name: httpd
        state: restarted

    - name: Create test PHP page
      copy:
        dest: /var/www/html/info.php
        content: "<?php phpinfo(); ?>"
...

